### ISSUE TITLE
Determine the origin of this error

### ISSUE THREAD

**Issue by philngo** [impactlab/oeem-energy-datastore#33]
Saw this error when using the command `./manage.py runmeter`

```
Running meter for Project 9f38e527-5f1d-42e1-bc13-5b12bfac9ab0
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/conda/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/conda/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/conda/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/conda/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/code/datastore/management/commands/runmeter.py", line 11, in handle
    project.run_meter()
  File "/code/datastore/models.py", line 137, in run_meter
    meter_results = meter.evaluate(DataCollection(project=project))
  File "/opt/conda/lib/python3.5/site-packages/eemeter/meter/default.py", line 609, in evaluate
    return super(DefaultResidentialMeter, self).evaluate(data_collection)
  File "/opt/conda/lib/python3.5/site-packages/eemeter/meter/base.py", line 544, in evaluate
    outputs = self.meter.evaluate(data_collection)
  File "/opt/conda/lib/python3.5/site-packages/eemeter/meter/control.py", line 47, in evaluate
    meter_result = meter.evaluate(input_data_collection)
  File "/opt/conda/lib/python3.5/site-packages/eemeter/meter/base.py", line 403, in evaluate
    outputs_dict = self.evaluate_raw(**all_inputs)
  File "/opt/conda/lib/python3.5/site-packages/eemeter/meter/library.py", line 727, in evaluate_raw
    c.filter_by_period(project.baseline_period)
  File "/opt/conda/lib/python3.5/site-packages/eemeter/consumption.py", line 698, in filter_by_period
    filtered_data = self.data[:period.end].copy()
  File "/opt/conda/lib/python3.5/site-packages/pandas/core/series.py", line 601, in __getitem__
    return self._get_with(key)
  File "/opt/conda/lib/python3.5/site-packages/pandas/core/series.py", line 606, in _get_with
    indexer = self.index._convert_slice_indexer(key, kind='getitem')
  File "/opt/conda/lib/python3.5/site-packages/pandas/indexes/base.py", line 1047, in _convert_slice_indexer
    self._validate_indexer('slice', key.stop, kind),
  File "/opt/conda/lib/python3.5/site-packages/pandas/indexes/base.py", line 2738, in _validate_indexer
    self._invalid_indexer(form, key)
  File "/opt/conda/lib/python3.5/site-packages/pandas/indexes/base.py", line 1117, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.indexes.range.RangeIndex'> with these indexers [2011-09-20 00:00:00+00:00] of <class 'datetime.datetime'>
```

**Comment by philngo** [comment]
Hmm... Could not reproduce this error upon rerunning the meter. Maybe that means it had something to do with running the meter and the uploader simultaneously, which was the case when I got this error but was not the case when trying to reproduce it today.
